language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install -e ."
  - "pip install -r requirements.txt"
script: nosetests --with-coverage --cover-erase --cover-package=pysharedutils
after_success: coveralls
